---
- name: Download foo.conf
  get_url:
    url: https://github.com/dkasyan/Ferm/archive/master.zip
    dest: /home/pi/
    mode: '0777'

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/Ferm-master.zip
    dest: /home/pi/deploy-folder/
    group: pi
    remote_src: yes
#Skopiuj systemct
#Skopiuj zawartość gita
#Zresetuj systemct startujac projekt 